name: workhorse

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 6 * * Mon-Fri"
  workflow_dispatch: {}

jobs:
  workhorse:
    runs-on: ubuntu-latest
    steps:
    - uses: dropseed/workhorse@v0
      with:
        plans: "merge-deps"
        github_token: ${{ secrets.YOUR_ORG_TOKEN }}
